### ISSUE TITLE
Huggingface

### ISSUE THREAD

**Issue by flozi00** [tatp22/linformer-pytorch#3]
Could you integrate this model into the huggingface transformers repository ?
It would be a great addition there

**Comment by tatp22** [comment]
Hi @flozi00! I am not done with my implementation right now, and I don't want to migrate stuff out of this repository until I am done with what I want to finish. When I am finished, I will investigate this further.

**Comment by flozi00** [comment]
Great,
I think the biggest task would be the formatting of the code.

Do you have experience about the model performance on squad question answering dataset ?

**Comment by tatp22** [comment]
No clue. I am not using this self attention for this reason, so I don't think I would know.

There may be some templates for how to add new codes to help with that, but as I said, I will not look into this until I have implemented some more things.
